package soham_common_req_keys

const (
	WHATSAPP_CLIENT_TOKEN_KEY = "UUID_AUTH"
	WHATSAPP_CLIENT_NUM_KEY   = "NUMBER_AUTH"
)
const (
	ERROR_INVALID_UUID_TOKEN         = 203
	ERROR_NUMBER_TOKEN_NOT_PASSED    = 204
	ERROR_GENERATE_TOKEN_MISMATCH    = 205
	ERROR_MISMATCH_NUMBER_FROM_TOKEN = 206
	ERROR_INVALID_WEB_MEDIA_LINK     = 207
)
