package ecommerce_erptables

type ItemGroupERPTableStruct struct {
	Igroupid   int     `json:"igroupid"`
	IGROUP     string  `json:"IGROUP"`
	PNAME      string  `json:"PNAME"`
	UNDERID    int     `json:"UNDERID"`
	ITNAME     string  `json:"ITNAME"`
	LTAX       float64 `json:"LTAX"`
	CTAX       float64 `json:"CTAX"`
	GP         float64 `json:"GP"`
	OBAL       float64 `json:"OBAL"`
	CBAL       float64 `json:"CBAL"`
	SACNO      int     `json:"SACNO"`
	PACNO      int     `json:"PACNO"`
	STSACNO    int     `json:"STSACNO"`
	STPACNO    int     `json:"STPACNO"`
	IACNO      int     `json:"IACNO"`
	RACNO      int     `json:"RACNO"`
	CCODE      string  `json:"CCODE"`
	STVAL      int     `json:"STVAL"`
	DIV        float64 `json:"DIV"`
	INTO       float64 `json:"INTO"`
	UNITID     int     `json:"UNITID"`
	DBHAV      string  `json:"DBHAV"`
	GWTNWT     int     `json:"GWTNWT"`
	STAMPID    int     `json:"STAMPID"`
	ITYPE      int     `json:"ITYPE"`
	DEL        string  `json:"DEL"`
	TTYPE      int     `json:"TTYPE"`
	ALTTAG     int     `json:"ALTTAG"`
	SRTOTAL    float64 `json:"SRTOTAL"`
	SRDAMT     float64 `json:"SRDAMT"`
	SRSAMT     float64 `json:"SRSAMT"`
	SRLAMT     float64 `json:"SRLAMT"`
	SRMAMT     int     `json:"SRMAMT"`
	EXTOTAL    float64 `json:"EXTOTAL"`
	EXLAMT     float64 `json:"EXLAMT"`
	EXMAMT     int     `json:"EXMAMT"`
	EXDAMT     float64 `json:"EXDAMT"`
	EXSAMT     float64 `json:"EXSAMT"`
	MRPTYPE    int     `json:"MRPTYPE"`
	DIVIDERATE float64 `json:"DIVIDERATE"`
	INTORATE   float64 `json:"INTORATE"`
	PURLESS    float64 `json:"PURLESS"`
	DIS        float64 `json:"DIS"`
	SMDET      string  `json:"SMDET"`
	RTAG       int     `json:"RTAG"`
	MINQTY     float64 `json:"MINQTY"`
	POINT      float64 `json:"POINT"`
	RESDRATE   string  `json:"RESDRATE"`
	RESSRATE   string  `json:"RESSRATE"`
	RESMRATE   string  `json:"RESMRATE"`
	RESLBR     string  `json:"RESLBR"`
	Resigrp    string  `json:"resigrp"`
	CPOINT     float64 `json:"CPOINT"`
	IRLEVEL    int     `json:"IRLEVEL"`
	VRATE      float64 `json:"VRATE"`
	IGTUNCH    float64 `json:"IGTUNCH"`
	IGTGNUM    int     `json:"IGTGNUM"`
	MCXINTO    float64 `json:"MCXINTO"`
	MCXCOMEX   int     `json:"MCXCOMEX"`
	LBRDIS     int     `json:"LBRDIS"`
	ITRATE     int     `json:"ITRATE"`
	UPMRP      string  `json:"UPMRP"`
	IGALADD    int     `json:"IGALADD"`
	RESMRP     int     `json:"RESMRP"`
	RESLESS    int     `json:"RESLESS"`
	CONSUME    int     `json:"CONSUME"`
	UPSALE     string  `json:"UPSALE"`
	RENTACNO   int     `json:"RENTACNO"`
	PSGST      float64 `json:"PSGST"`
	PCGST      float64 `json:"PCGST"`
	PIGST      float64 `json:"PIGST"`
	HSNCODE    string  `json:"HSNCODE"`
	JHSNCODE   string  `json:"JHSNCODE"`
	GSTNAME    string  `json:"GSTNAME"`
	Defino     int     `json:"defino"`
}
