package env

const app_ENV_KEY = "APP_ENV"
const port_KEY = "PORT"
const MONGO_URL_KEY = "MONGO_URL"
const MONGO_DB_NAME_KEY = "MONGO_DB_NAME"
const access_TOKEN_KEY = "ACCESS_TOKEN_KEY"
const refresh_TOKEN_KEY = "REFRESH_TOKEN_KEY"
const FIREBASE_JSON_STRING_KEY = string("FIREBASE_JSON_STRING")
const FIREBASE_DATABASE_URL_KEY = "FIREBASE_DATABASE_URL"
const REDIS_DB_HOST_KEY = "REDIS_DB_HOST"
const REDIS_DB_PORT_KEY = "REDIS_DB_PORT"
const REDIS_DB_PASSWORD_KEY = "REDIS_DB_PASSWORD"
const REDIS_DB_DATABASE_KEY = "REDIS_DB_DATABASE"

const RequestTokenHeaderKey = "X-Api-Token"
